# Quiz
primaryColor = "#088B36"
secondaryColor = "#9ED29C"
titleImage = "grasslogo.svg"
titleImageWidth = "78px"
titleImageHeight = "78px"
quizImage = "zmi_stone_town_opendronemap_v_surf_icw.png"
quizCardWidth = "450px"
quizTitle = "GRASS GIS Quiz"
quizSubtitle = "by tmszi"
answersPerQuestion = 3
correctAnswer = "correct"

# Quiz questions with answers
# Correct question answer has value = correctAnswer

# First question
[[quiz]]
question = "What is the actual GRASS GIS stable release?"
label = "7.8.7" # first answer label
value = "7.8.7" # first answer value

[[quiz]]
question = "What is the actual GRASS GIS stable release?"
label = "8.0.0" # second answer label
value = "8.0.0" # second answer value

[[quiz]]
question = "What is the actual GRASS GIS stable release?"
label = "8.2.0" # third answer label
value = "correct" # third answer value

# Second question
[[quiz]]
question = "Under what license is GRASS GIS released?"
label = "GNU LGPL" # first answer label
value = "GNU LGPL" # first answer value

[[quiz]]
question = "Under what license is GRASS GIS released?"
label = "GNU AGPL" # second answer label
value = "GNU AGPL" # second answer value

[[quiz]]
question = "Under what license is GRASS GIS released?"
label = "GNU GPL" # third answer label
value = "correct" # third answer value

# Third question
[[quiz]]
question = "What kind of Python GUI library GRASS GIS use?"
label = "Tkinter" # first answer label
value = "Tkinter" # first answer value

[[quiz]]
question = "What kind of Python GUI library GRASS GIS use?"
label = "wxPython" # second answer label
value = "correct" # second answer value

[[quiz]]
question = "What kind of Python GUI library GRASS GIS use?"
label = "Kivy" # third answer label
value = "Kivy" # third answer value