---
name: Run tests

# Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: ${{ matrix.name }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}-${{
        matrix.name }}
      cancel-in-progress: true

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        include:
          - name: '22.04'
            os: ubuntu-22.04
            config: ubuntu-22.04
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}

      - name: Get app dependencies
        run: |
          .github/workflows/install_dependencies.sh

      - name: Get app JavaScript dependencies
        run: |
          yarn global add @quasar/cli npx
          yarn

      - name: Run component tests with Mozilla Firefox web browser
        run: |
          firefox --version
          npx cypress run --component --browser $(which firefox)

      - name: Run component tests with Google Chome web browser web browser
        run: |
          google-chrome-stable --version
          npx cypress run --component --browser $(which google-chrome-stable)

      - name: Run component tests with Microsoft Edge web browser
        run: |
          microsoft-edge --version
          npx cypress run --component --browser $(which microsoft-edge)

      - name: Run app web server in background for e2e tests
        run: |
          npx quasar dev &

      - name: Run e2e/unit tests with Mozilla Firefox web browser
        run: |
          firefox --version
          npx cypress run --e2e --browser $(which firefox)

      - name: Run e2e/unit tests with Google Chome web browser web browser
        run: |
          google-chrome-stable --version
          npx cypress run --e2e --browser $(which google-chrome-stable)

      - name: Run e2e/unit tests with Microsoft Edge web browser
        run: |
          microsoft-edge --version
          npx cypress run --e2e --browser $(which microsoft-edge)

  push_docker_img:
      runs-on: ubuntu-
      needs: [build-and-test]

      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Get Docker image version
          run: |
            .github/workflows/get_docker_image_tag_number.sh

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./docker/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:${DOCKERHUB_IMAGE_VERSION}